services:
  bridge-bank:
    image: daalves/bridge-bank:latest
    container_name: bridge-bank
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/compose:ro
    ports:
      - "3002:3000"

  watchtower:
    image: containrrr/watchtower
    container_name: bridge-bank-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400 --http-api-update --http-api-periodic-polls bridge-bank
    environment:
      - WATCHTOWER_LOG_LEVEL=warn
      - WATCHTOWER_HTTP_API_TOKEN=bridge-bank-update
