services:
  bridge-bank:
    image: daalves/bridge-bank:latest
    container_name: bridge-bank
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data

    # Uncomment if Actual Budget is on a named Docker network:
    # networks:
    #   - your_actual_network

# networks:
#   your_actual_network:
#     external: true
