services:
  bridge-bank:
    image: daalves/bridge-bank:latest
    container_name: bridge-bank
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/compose:ro
    ports:
      - "3000:3000"
